USE GestionEscolar;
CREATE KEYSPACE GestionEscolar WITH REPLICATION = {'class':'SimpleStrategy', 'replication_factor':1};

DROP TABLE ALUMNO;
CREATE TABLE ALUMNO(
CURP VARCHAR PRIMARY KEY,
NOMBRE VARCHAR,
FECHANAT VARCHAR,
FECHAINSCRIPCION VARCHAR,
GRADOACADEMICO VARCHAR,
TUTOR VARCHAR,
CREDITOTUTORIA BOOLEAN,
TUTORIAFIRMADA BOOLEAN,
ESCUELA VARCHAR,
);

CREATE TABLE ADMINISTRATIVOS(
CURP VARCHAR PRIMARY KEY,
NOMBRE VARCHAR,
TELEFONO VARCHAR,
NOCUENTABANCARIA VARCHAR,
FUNCION VARCHAR,
HORAENTRADA VARCHAR,
HORASALIDA VARCHAR,
EXTENSIONTEL VARCHAR,
CORREO VARCHAR,
ESCUELA VARCHAR
);

DROP TABLE DOCENTES;
CREATE TABLE DOCENTES(
CURP VARCHAR PRIMARY KEY,
NOMBRE VARCHAR,
TELEFONO VARCHAR,
NOCUENTABANCARIA VARCHAR,
NOOFICINA INT,
ESPECIALIDAD VARCHAR,
GRADOESTUDIO VARCHAR,
TUTORADOS LIST<VARCHAR>,
TUTORIAFIRMADA BOOLEAN,
ESCUELA VARCHAR
);

create table ESCUELAS(
CLAVE VARCHAR PRIMARY KEY,
NOMBRE VARCHAR,
DIRECCION VARCHAR,
CIUDAD VARCHAR,
ADMINISTRATIVOS LIST<VARCHAR>,
DOCENTES LIST<VARCHAR>,
MANTENIMIENTO LIST<VARCHAR>,
ALUMNOS LIST<VARCHAR>
);

DROP TABLE MANTENIMIENTO;
CREATE TABLE MANTENIMIENTO(
CURP VARCHAR PRIMARY KEY,
NOMBRE VARCHAR,
TELEFONO VARCHAR,
TELINSTITUCIONAL VARCHAR,
ESPECIALIDAD VARCHAR,
ESCUELA VARCHAR,
nocuentabancaria VARCHAR
);


DROP TABLE alumnos_tutor;
CREATE TABLE alumnos_tutor(
CURP VARCHAR,
NOMBRE VARCHAR,
FECHANAT VARCHAR,
FECHAINSCRIPCION VARCHAR,
GRADOACADEMICO VARCHAR,
TUTOR VARCHAR,
CREDITOTUTORIA BOOLEAN,
TUTORIAFIRMADA BOOLEAN,
ESCUELA VARCHAR,
PRIMARY KEY(TUTOR, CURP)
);


DROP TABLE docentes_escuela;
CREATE TABLE docentes_escuela(
CURP VARCHAR,
NOMBRE VARCHAR,
TELEFONO VARCHAR,
NOCUENTABANCARIA VARCHAR,
NOOFICINA INT,
ESPECIALIDAD VARCHAR,
GRADOESTUDIO VARCHAR,
TUTORADOS LIST<VARCHAR>,
TUTORIAFIRMADA BOOLEAN,
ESCUELA VARCHAR,
PRIMARY KEY(ESCUELA, CURP)
);

DROP TABLE administrativos_escuela;
CREATE TABLE administrativos_escuela(
CURP VARCHAR,
NOMBRE VARCHAR,
TELEFONO VARCHAR,
NOCUENTABANCARIA VARCHAR,
FUNCION VARCHAR,
HORAENTRADA VARCHAR,
HORASALIDA VARCHAR,
EXTENSIONTEL VARCHAR,
CORREO VARCHAR,
ESCUELA VARCHAR,
PRIMARY KEY(ESCUELA, CURP)
);